name: Test Files - Full Schema Validation

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-passing-json-schema-validation:
    name: JSON Types - Passing Validation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Let all matrix combinations run regardless of fails
      matrix:
        files:
          - |
            test-files/json/good_1.json
            test-files/json/good_2.json
            test-files/json/good_3.json
          - |
            test-files/yaml/good_1.yaml
            test-files/yaml/good_2.yaml
            test-files/yaml/good_3.yaml
          - |
            test-files/toml/good_1.toml
            test-files/toml/good_2.toml
            test-files/toml/good_3.toml
          - |
            test-files/toml/good_1.toml
            test-files/toml/good_2.toml
            test-files/toml/good_3.toml
            test-files/yaml/good_1.yaml
            test-files/yaml/good_2.yaml
            test-files/yaml/good_3.yaml
            test-files/json/good_1.json
            test-files/json/good_2.json
            test-files/json/good_3.json
        schemas:
          - test-files/json/person.schema.json
          - test-files/yaml/person.schema.yaml
          - test-files/toml/person.schema.toml
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
      
      - name: Test Schema Validation
        id: test-schema
        uses: ./
        with:
          files: ${{ matrix.files }}
          schema-file: ${{ matrix.schemas }}
      
      - name: Test Schema Validation w/ URL
        id: test-schema-url
        uses: ./
        with:
          files: ${{ matrix.files }}
          schema-url: https://raw.githubusercontent.com/chase-roohms/schema-validator/${{ github.ref }}/${{ matrix.schemas }}
  
  test-failing-json-schema-validation:
    name: JSON Types - Failing Validation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Let all matrix combinations run regardless of fails
      matrix:
        files:
          - |
            test-files/json/bad_1.json
            test-files/json/bad_2.json
            test-files/json/bad_3.json
          - |
            test-files/yaml/bad_1.yaml
            test-files/yaml/bad_2.yaml
            test-files/yaml/bad_3.yaml
          - |
            test-files/toml/bad_1.toml
            test-files/toml/bad_2.toml
            test-files/toml/bad_3.toml
          - |
            test-files/toml/bad_1.toml
            test-files/toml/bad_2.toml
            test-files/toml/bad_3.toml
            test-files/yaml/bad_1.yaml
            test-files/yaml/bad_2.yaml
            test-files/yaml/bad_3.yaml
            test-files/json/bad_1.json
            test-files/json/bad_2.json
            test-files/json/bad_3.json
        schemas:
          - test-files/json/person.schema.json
          - test-files/yaml/person.schema.yaml
          - test-files/toml/person.schema.toml
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
      
      - name: Test Schema Validation
        id: test-schema
        continue-on-error: true
        uses: ./
        with:
          files: ${{ matrix.files }}
          schema-file: ${{ matrix.schemas }}
      
      - name: Fail if any validation passed
        if: ${{ steps.test-schema.outcome == 'success' }}
        run: exit 1
    
  test-passing-xml-schema-validation:
    name: XML Types - Passing Validation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Let all matrix combinations run regardless of fails
      matrix:
        files:
          - |
            test-files/xml/good_1.xml
            test-files/xml/good_2.xml
            test-files/xml/good_3.xml
        schemas:
          - test-files/xml/person.schema.xml
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
      
      - name: Test Schema Validation
        id: test-schema
        uses: ./
        with:
          files: ${{ matrix.files }}
          schema-file: ${{ matrix.schemas }}
      
      - name: Test Schema Validation w/ URL
        id: test-schema-url
        uses: ./
        with:
          files: ${{ matrix.files }}
          schema-url: https://raw.githubusercontent.com/chase-roohms/schema-validator/${{ github.ref }}/${{ matrix.schemas }}
    
  test-failing-xml-schema-validation:
    name: XML Types - Failing Validation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Let all matrix combinations run regardless of fails
      matrix:
        files:
          - |
            test-files/xml/bad_1.xml
            test-files/xml/bad_2.xml
            test-files/xml/bad_3.xml
        schemas:
          - test-files/xml/person.schema.xml
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
      
      - name: Test Schema Validation
        id: test-schema
        continue-on-error: true
        uses: ./
        with:
          files: ${{ matrix.files }}
          schema-file: ${{ matrix.schemas }}
      
      - name: Fail if any validation passed
        if: ${{ steps.test-schema.outcome == 'success' }}
        run: exit 1