name: Test Full Schema Validation

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-passing-schema-file-validation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        files:
          - test-files/json/good_1.json
            test-files/json/good_2.json
            test-files/json/good_3.json
          - test-files/yaml/good_1.yaml
            test-files/yaml/good_2.yaml
            test-files/yaml/good_3.yaml
          - test-files/toml/good_1.toml
            test-files/toml/good_2.toml
            test-files/toml/good_3.toml
        schemas:
          - test-files/json/person.schema.json
          - test-files/yaml/person.schema.yaml
          - test-files/toml/person.schema.toml
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
      
      - name: Test Schema Validation
        uses: ./
        with:
          files: ${{ matrix.files }}
          schema-file: ${{ matrix.schemas }}